name: GitOps

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python for use with actions
      uses: actions/setup-python@v1.0.0
    - name: Install client-python from civo
      run: pip install git+https://github.com/civo/client-python.git
    - name: Run check script
      env:
        CIVO_TOKEN: ${{ secrets.CIVO_TOKEN }}
      run: python check.py
    - name: Add ssh preivate key to the server
      run: |
        mkdir -p $HOME/.ssh
        chmod 700 $HOME/.ssh
        echo -n "${{ secrets.SSH_KEY_PRIVATE }}" | base64 --decode > $HOME/.ssh/id_rsa,
        chmod 600 $HOME/.ssh/id_rsa,
        stat $HOME/.ssh/id_rsa
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
