name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    with:
      python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
    - name: Install client-python from civo
      run: pip install git+https://github.com/civo/client-python.git
    - name: Run check script
      run: python check.py
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
